"""Plot 5-year cumulative revenue comparison using real simulation CSV data.

This script reads CSV files generated by the simulator's DataLogger
(which is aligned with the reference repo's format) and plots cumulative
revenue curves for Baseline, PPO-RL, and PPO+TTM.

Revenue is calculated the same way as the reference repo's analysis module:
- Each row has a `profit` column = sum of fares from in-progress jobs at that step
- Cumulative revenue = running sum of per-step profit
- X-axis = time in years (1 step = 1 hour → 8760 steps/year)
"""

import csv
import numpy as np
import matplotlib.pyplot as plt
import os


def load_cumulative_revenue(filename, dt=1):
    """Load revenue from CSV, returning cumulative sum sampled weekly."""
    revenue = []
    with open(filename, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        r = 0
        for idx, datum in enumerate(reader):
            r += float(datum["profit"])
            # Sample weekly (every 168 hours)
            if idx % (24 * 7 * dt) == 0:
                revenue.append(r)
    t = np.linspace(0, len(revenue) / 52, len(revenue))
    return t, np.array(revenue)


def main():
    files = {
        "Baseline (80-20)": "output_baseline_real.csv",
        "PPO-RL": "output_ppo_real.csv",
        "PPO+TTM (Our Work)": "output_ppo_ttm_real.csv",
    }

    colors = {
        "Baseline (80-20)": "#1f77b4",
        "PPO-RL": "#ff7f0e",
        "PPO+TTM (Our Work)": "#2ca02c",
    }

    fig, ax = plt.subplots(figsize=(8, 4.5))

    for label, filename in files.items():
        if os.path.exists(filename):
            print(f"Plotting {label} from {filename}...")
            t, revenue = load_cumulative_revenue(filename)
            ax.plot(t, revenue, label=label, linewidth=2, color=colors[label])
            print(f"  -> Final {label} Revenue: ${revenue[-1]:,.2f}")
        else:
            print(f"Warning: {filename} not found. Skipping {label}.")

    ax.set_xlabel("Years")
    ax.set_ylabel("Cumulative Revenue ($)")
    ax.set_title("5-Year Revenue Comparison (Real Simulation Data)")
    ax.grid(True, linestyle='--', alpha=0.3)
    ax.legend(loc="upper left")

    plt.tight_layout()
    plt.savefig("real_comparison_plot.png", dpi=200)
    print("Saved plot to real_comparison_plot.png")
    plt.show()


if __name__ == "__main__":
    main()
