use_ttm: false

delta t: 3600      # Seconds

start t: 2008/12/31 22:20:23
end t: 2014/01/01 18:20:15
max steps: 50000

city: data/nyc-map.pkl
demand: data/nyc-demand.csv

fleet:
  size: 50
  vehicle: BYD E6
  battery model: multistage
  depot: none

charging stations:
  - location: 208
    max port power: 10
    max total power: 500
    efficiency: 0.9
    ports: 10
    max total power: 50
  - location: 1
    max port power: 50
    max total power: 500
    efficiency: 0.9
    ports: 10
